delete pp_worddb;
delete pp_wordtag;
delete pp_language;
delete pp_user;
delete pp_usertag;
insert into pp_language values (1,'EN');
insert into pp_language values (2,'DE');
insert into pp_wordtag values (1,'germanBase',1);
insert into pp_wordtag values (2,'germanAdvanced',1);
insert into pp_wordtag values (3,'katkaZakladyNemciny',2);
insert into pp_worddb values (1,'ahoj','hallo',2);
insert into pp_worddb values (2,'cau','cus',1);
insert into pp_worddb values (3,'sak','sack',2);
insert into pp_worddb values (4,'vajcia','eier',2);
insert into pp_worddb values (5,'spandau','icke',2);
insert into pp_worddb values (6,'fikat','bumsen',3);
insert into pp_worddb values (7,'pichat ','ficken',3);
insert into pp_user values (1,'anonymousUser','anonymousUser');
insert into pp_user values (2,'tomas','tom');
insert into pp_user values (3,'katka','kat');
insert into pp_usertag values (2,1);
insert into pp_usertag values (2,2);
insert into pp_usertag values (3,3);
insert into pp_usertag values (1,1);
insert into pp_usertag values (1,2);
delete from pp_userword where word_id not in worddb;
delete from pp_usertag where tag_id not in tag;
